# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


############################
## TITLE AND ROOT
############################

# website title/name
title: Thomas Ekström Hansen

# root of the website, should contain a trailing slash
baseURL: 'https://codingcellist.github.io/'


############################
## LANGUAGE
############################

# use EN by default and not DA
defaultContentLanguage: en

# does this site use Chinese, Japanese, and/or Korean?
hasCJKLanguage: false

# default content is in content/en
defaultContentLanguageInSubdir: true

removePathAccents: true


############################
## COLLECTIONS
############################

# https://docs.hugoblox.com/reference/page-features/#how-to-configure-a-page-collection
cascade:
  # Configure blog posts
  - _target:
      path: /post/**
    pager: true
    editable: false
    reading_time: false
    commentable: false
    show_related: true
    # whether to show a path-like thing at the top
    show_breadcrumb: false
    share: false
    # whether to show the menu-/nav-bar at the top of each blog page
    header:
      navbar:
        enable: true


############################
## ADVANCED
############################

# get latest update info from git?
enableGitInfo: true

# summary length in words
summaryLength: 30

# #items per page in paginated lists
paginate: 10

enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

permalinks:
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'

disableAliases: true

outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart

timeout: 600000

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

markup:
  _merge: deep

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep

