# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/


# Default language
en:
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  params:
    languageCode: en-gb
    description: "Thomas Ekström Hansen's personal website"

da:
  contentDir: content/da
  params:
    language-code: da
    description: "Thomas Ekström Hansens personlige hjemmeside"
  menu:
    main:
      - name: "Forside"
        url: "#about"
        weight: 10

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
