# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


# Appearance

appearance:
  # The settings below seem to still work but have gotten obliterated from the
  # docs and replaced by "Just DIY with custom CSS 4head"  -_-

  theme_day: coffee
  theme_night: dark

  font: minimal

  # XS | S | M | L | XL
  font_size: L


# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true


# Site Footer

footer:
  # LICENSE: This website is licensed under CC-BY-SA
  copyright:
    notice: '© 2021-{year} Thomas E. Hansen. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true


# Localisation

locale:
  # NOTE: **must** refer to Monday the 2nd of January 2006
  date_format: 'Mon, 2 Jan 2006'
  # NOTE: **must** refer to 15:04 or 3:04 PM
  time_format: '15:04'
  address_format: en-gb


# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula

  # LaTeX math rendering?
  math:
    enable: true

  privacy_pack:
    enable: false

  # TODO: ? Unsure what this does
  ## repository:
  ##   url: 'https://github.com/<username>/<repository>'
  ##   content_dir: content
  ##   branch: main

  avatar:
    # gravatar.com?
    gravatar: false
    shape: circle

  comment:
    provider: ''  # blank to disable
    ## disqus:
    ##   shortname: ''
    ##   show_count: true
    ## commento:
    ##   url: ''
    ## giscus:    # TODO: This might be interesting, but honestly, do I want it?
    ##   repo: ''
    ##   repo_id: ''
    ##   category: ''
    ##   category_id: ''
    # TODO: If I _do_ decide to enable commenting, see:
    #       * https://docs.hugoblox.com/reference/page-features/#how-to-configure-a-page-collection
    #       * https://docs.hugoblox.com/reference/comments/#choose-where-users-can-comment
    #       * https://gohugo.io/content-management/front-matter/#cascade

  search:
    provider: # blank to disable

  map:
    provider: ''  # blank to disable
  ##  api_key: ''
  ##  zoom: 15


extensions:
  cms:
    branch: main
    local_backend: false
  # https://jpswalsh.github.io/academicons/
  # (for the SciHub raven!)
  academicons:
    enable: true

